### ISSUE TITLE
Few changes

### ISSUE THREAD

**Issue by techieforgood** [bparikh99/webscraping#1]
Hi Bhavya. I am just creating this issue to list a few changes that I require in the script.

## Changes

1.  Can you add a new line to the frontmatter of every .md file ?
It should be this: 
`image: "images/img0.jpg"`
It's the same img0 on all files. So, you need not worry.
2.  Can you name each md file as `index.md` ? Currently they are name as {title}.md.
3.  Change how you retrieve the title.
Currently you are fetching the title from the page title (which is set the `<title>` tag in the `<head>` tag of the page). Instead can you fetch the title from the article ? Following sample screenshot shows the title located in an article.

![image](https://user-images.githubusercontent.com/111271571/196001277-1d3a9d0a-0dac-4aa8-b3cc-a4b5099b23e9.png)

**Comment by bparikh99** [comment]
Please refer to branch issue1 and resolve this issue as you mentioned Thanks!

**Comment by techieforgood** [comment]
Wow, you are great. Thanks for the quick fix Bhavya.

**Comment by bparikh99** [comment]
Please refer the change and close if it is appropriate

**Comment by techieforgood** [comment]
Sure. Looks good.
